- hosts: workstations
  become: no
  tasks:
    - name: Verify Tools Folder
      file: path="{{ansible_env.HOME}}/tools/" state=directory

    - name: Download RVM
      get_url:
        url: https://get.rvm.io
        dest: "{{ansible_env.HOME}}/tools/rvm_installer.sh"

    - name: Install RVM
      shell: "bash {{ansible_env.HOME}}/tools/rvm_installer.sh" 

    - name: Install 2.2.9
      shell: "{{ansible_env.HOME}}/.rvm/bin/rvm install 2.2.9"

    - name: Set Default Ruby
      shell: "{{ansible_env.HOME}}/.rvm/bin/rvm alias create default 2.2.9"

    - name: Install Homesick
      shell: "{{ansible_env.HOME}}/.rvm/rubies/ruby-2.2.9/bin/gem install homesick"

    - name: Clone my Homesick
      shell: "{{ansible_env.HOME}}/.rvm/gems/ruby-2.2.9/bin/homesick clone Blue-Dog-Archolite/homestick-dot-files"

    - name: Link my Homesick
      shell: "{{ansible_env.HOME}}/.rvm/gems/ruby-2.2.9/bin/homesick link homestick-dot-files --force"
