- hosts: workstations
  become: no
  tasks:
    - name: Verify Tools Folder
      file: path="{{ansible_env.HOME}}/tools/" state=directory
    - name: Download RVM
      get_url:
        url: https://get.rvm.io
        dest: "{{ansible_env.HOME}}/tools/rvm_installer.sh"
    - name: Install RVM
      shell: "bash {{ansible_env.HOME}}/tools/rvm_installer.sh" 
    - name: Install 2.2.9
      shell: "{{ansible_env.HOME}}/.rvm/bin/rvm install 2.2.9"
    - name: Set Default Ruby
      shell: "{{ansible_env.HOME}}/.rvm/bin/rvm --default use 2.2.9"
