- hosts: workstations
  become: no
  tasks:

    # - name: Download Linux Brew
    #   get_url: 
    #     url: https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh
    #     dest: "{{ansible_env.HOME}}/tools/linux-brew.sh"

    # - name: Install Linux Brew
    #   shell: "sh {{ansible_env.HOME}}/tools/linux-brew.sh"

    - name: Install LinuxBrew items
      shell: brew install {{item}}
      with_items:
        - fzf
        - gcc
        - rbenv
        - rbenv-gemset
        - ruby-build
        - z
