- hosts: workstations
  become: no
  tasks:

    - name: Download Linux Brew
      git:
        repo: 'https://github.com/Linuxbrew/brew.git'
        dest: "{{ansible_env.HOME}}/.linuxbrew/"
        update: yes

    - name: Install LinuxBrew items
      shell: "{{ansible_env.HOME}}/.linuxbrew/bin/brew install {{item}}"
      async: 2400
      poll: 5
      with_items:

        - fzf
        - gcc
        - rbenv
        - rbenv-gemset
        - ripgrep
        - ruby-build
        - z
