---
# Install required packages
- hosts: all
  # gather_facts: False

  pre_tasks:
    - name: 'Work around install aptitude'
      become: yes
      raw: sudo apt-get -y install aptitude
      when: ansible_distribution == "Ubuntu"

# Install for all hosts
- hosts: all
  roles:
    - pre-install
    - workstation
    - post-brew

# Install GUI components
- hosts: gui
  roles:
    - gui
  tags:
    - gui
