---
# Install required packages
- hosts: all
  gather_facts: False

  pre_tasks:
    - name: Install python for Ansible
      become: yes
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python2 python-simplejson)
      changed_when: False

    - name: Apt https transport install
      become: yes
      raw: apt install apt-transport-https -y

- hosts: all
  roles:
    - workstation

# Install GUI components
- hosts: gui
  roles:
    - gui
  tags:
    - gui
