- hosts: workstations
  become: no
  tasks:

    - name: pip installs
      become: yes
      shell: "pip install {{ item }}"
      with_items:
         - pipenv

    - name: Clone and Link Homesick
      shell: "{{ item }}"
      with_items:
         - homesick clone Blue-Dog-Archolite/homestick-dot-files
         - homesick link homestick-dot-files --force

    - name: Clone powerline-shell
      git:
        repo: https://github.com/b-ryan/powerline-shell
        dest: "{{ ansible_env.HOME }}/tools/powerline-shell"
        update: yes

    - name: Install Powerline Shell
      become: yes
      shell: chdir="{{ansible_env.HOME}}/tools/powerline-shell" python setup.py install --user

    - name: Create Vim2 PipFile Locations
      file:
        path: "{{ ansible_env.HOME }}/tools/vim2"
        state: directory
        recurse: yes

    - name: Create Vim3 PipFile Locations
      file:
        path: "{{ ansible_env.HOME }}/tools/vim3"
        state: directory
        recurse: yes

    - name: Create Vim2
      synchronize:
        src: "./pipfiles/vim2/"
        dest: "{{ ansible_env.HOME }}/tools/vim2/"

    - name: Create Vim3
      synchronize:
        src: "./pipfiles/vim3/"
        dest: "{{ ansible_env.HOME }}/tools/vim3/"
