- hosts: workstations
  become: yes
  tasks:
  - name: Create Docker Group
    group:
      name: docker
      state: present

  - name: Create RVM Group
    group:
      name: rvm
      state: present

  - name: Create VirtualBoxUsers Group
    group:
      name: vboxusers
      state: present

  - name: "Update uesrs to have 4096 key and rvm group"
    user:
      name: "{{ansible_user_id}}"
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
      append: yes
      groups: docker,rvm,disk,vboxusers
