---
- name: Upgrade Dist with Apt
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: Apt Installs Dependencies
  become: yes
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - libappindicator1
      - libgconf-2-4
      - libnss3   
