---
- name: Add Docker Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: latest

- name: Add Docker
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: latest
      filename: docker-stable
      update_cache: yes
