---
- name: Upgrade Dist with Apt
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    when: ansisble_distribution != "Ubuntu"


- name: Apt Installs
  become: yes
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
