---
- name: Create shared directories
  become: yes
  file:
    path: "{{ sharedInstallPath }}/tools/"
    state: directory
    mode: 0777
    recurse: yes

- name: Create user directories for Dein
  become: yes
  file:
    path: "~/tools/"
    state: directory
    mode: 0777
    recurse: yes