---
- name: manually update apt-key until bus is fixed
  become: yes
  apt:
    upgrade: dist

- name: Apt Installs
  become: yes
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
