---
- name: Manually update apt-key until bus is fixed
  shell: apt update
  become: yes

- name: Apt Installs GUI tools
  become: yes
  apt:
    state: present
    name:

      - cinnamon-desktop-environment
      - clipit
      - flameshot
      - gkrellm
      - google-chrome-stable
      - kdiff3
      - kleopatra
      - lightdm
      - rhythmbox
      - ulauncher

- name: Install snapd
  shell: "snap install snapd"
  become: yes
  when: ansible_virtualization_type != "wsl" or ansible_virtualization_type != "NA"
  #Normally the virtualization type on wsl should say wsl but
  #I have seen it show "NA"
