---
- name: Manually update apt-key until bus is fixed
  shell: apt update
  become: yes

- name: Apt Installs GUI tools
  become: yes
  apt:
    state: absent
    name:

            #- cinnamon-desktop-environment
            #- clipit
        #- flameshot
        #- gkrellm
        #- google-chrome-stable
        #- kdiff3
        #- kleopatra
        #- lightdm
        #- rhythmbox
      - ulauncher
