---
- name: Manually update apt-key until bus is fixed
  shell: apt update
  become: yes

- name: Apt Installs GUI tools
  become: yes
  apt:
    state: present
    name:
      - clipit
      - gkrellm
      - gnome-do
      - google-chrome-stable
      - kdiff3
      - kleopatra
      - rhythmbox
