- name: Download Keybase
  get_url:
    url: 'https://prerelease.keybase.io/keybase_amd64.deb'
    dest: "{{sharedInstallPath}}/tools/keybase.deb"

- name: Install Keybase
  shell: "dpkg -i {{sharedInstallPath}}/tools/keybase.deb"
  become: yes

- name: Update and Set Keybase
  shell: "apt-get install -f"
  become: yes
