---
- name: Apt Installs GUI tools
  become: yes
  pacman:
    state: present
    name:
      - clipit
      - gkrellm
      - gnome-do
      # - google-chrome-stable
      - kdiff3
      - kleopatra
      - rhythmbox
