---

- name: manually update apt-key until bus is fixed
  become: yes
  apt:
    upgrade: dist

- name: Apt Installs
  become: yes
  apt:
    state: present
    name:

      - build-essential
      - clamav
      - clamtk
      - ctags
      - fish
      - fonts-powerline
      - git
      - htop
      - mlocate
      - net-tools
      - python-dev
      - rbenv
      - ruby
      - ruby-dev
      - snapd
      - sysstat
      - terminator
      - thefuck
      - tmux
      - vim
      - yarn
