---

- name: manually update apt-key until bus is fixed
  become: yes
  apt:
    upgrade: dist

- name: Apt Installs
  become: yes
  apt:
    state: present
    name:

      - apt-transport-https
      - build-essential
      - ca-certificates
      - clamav
      - clamtk
      - ctags
      - curl
      - fish
      - fonts-powerline
      - git
      - htop
      - mlocate
      - python-dev
      - rbenv
      - ruby
      - ruby-dev
      - snapd
      - software-properties-common
      - sysstat
      - thefuck
      - tmux
      - vim
      - yarn
