---
- name: Make LinuxBrew directory
  become: yes
  file:
    path: /home/linuxbrew/.linuxbrew/
    state: directory
    mode: 0557



- name: Clone Install LinuxBrew
  become: yes
  git:
    repo: 'https://github.com/Homebrew/brew'
    dest: '/home/linuxbrew/.linuxbrew'
    update: yes

- name: Update profile for LinuxBrew
  raw: |
    test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
    echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile

# - name: Correct LinuxBrew Permissions
#   become: no
#   raw: |
#     chown -R $(whoami) /usr/local/var/homebrew

# - name: Set symlink for homebrew
#   become: yes
#   file:
#     src: /home/linuxbrew/.linuxbrew/bin/brew
#     dest: /usr/local/bin/brew
#     state: link

