---
- include_tasks: apt-repos.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: apt-install.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: pacman-install.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: curl-install.yml
- include_tasks: gem-installs.yml
- include_tasks: tmux-manager-install.yml
- include_tasks: setup-groups.yml
- include_tasks: homesick-install.yml

