---
# - name: Is brew installed
#   raw: |
#     hash brew 2> /dev/null
#   register: brew_installed
#   ignore_errors: True
#
- name: 'Brew install'
  raw: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: ansible_distribution == "Ubuntu"

- name: 'Add Brew to Path'
  raw: echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /$HOME/.profile && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
  when: ansible_distribution == "Ubuntu"

- name: Brew install needs system ruby and gcc
  raw: brew vendor-install ruby

- name: Install LinuxBrew items
  # when: brew_installed is True
  homebrew:
    state: present
    name:

      - ag
      - asdf
      - black
      - direnv
      - fzf
      - gcc
      - k9s
      - npm
      - nvim
      - pipenv
      - rbenv
      - rg
      - ruby-build
      - z
